networks:
  default:
    external:
      name: int371-network
services:
  nginx:
    image: nginx:1.19.10-alpine
    container_name: reverse-proxy
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
