networks:
  default:
    external:
      name: int371-network
services:
  nginx:
    image: nginx:1.19.10-alpine
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
